
GET http://localhost:3000/
x-api-key: SECRET
user-agent: Chrome

### forbidden

GET http://localhost:3000
x-api-key: INCORRECT


### get emoji by index

GET http://localhost:3000/?index=1
x-api-key: SECRET
user-agent: Chrome

