name: Test

on:
  push:
    branches:
      - main
    pull_request:
      branches: ['*']

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - name: Run unit tests
        run: pnpm test
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - name: Run e2e tests
        run: pnpm test:e2e
